version: "3.8"

services:
  postgres:
    container_name: arbob-postgres-prod
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: israr123
      POSTGRES_DB: Arbob
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    container_name: arbob-backend-prod
    image: israrahmad/arbob-tech-backend:latest
    environment:
      DATABASE_URL: postgresql://postgres:israr123@postgres:5432/Arbob?schema=public
      JWT_SECRET: hello123hdjmaKJGVSFFSKHKHSK
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
      HOST_URL: http://3.109.209.75:3000
      CORS_ORIGIN: http://3.109.209.75
      API_URL: http://3.109.209.75:3000
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    container_name: arbob-frontend-prod
    image: israrahmad/arbob-tech-frontend:latest
    environment:
      NODE_ENV: production
      REACT_APP_API_URL: http://3.109.209.75:3000
      REACT_APP_BASE_URL: http://3.109.209.75:3000
      REACT_APP_API_BASE_URL: http://3.109.209.75:3000
      REACT_APP_BACKEND_URL: http://3.109.209.75:3000
      PUBLIC_URL: http://3.109.209.75
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    name: arbob-network-prod
    driver: bridge

volumes:
  postgres_data:
