version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: israr123
      POSTGRES_DB: Arbob
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

  backend:
    image: israrahmad/arbob-tech-backend:latest
    environment:
      DATABASE_URL: postgresql://postgres:israr123@postgres:5432/Arbob
      JWT_SECRET: your_jwt_secret_here
      NODE_ENV: production
      PORT: 3000
      HOST_URL: http://3.109.209.75:3000
      CORS_ORIGIN: http://3.109.209.75
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    image: israrahmad/arbob-tech-frontend:latest
    environment:
      NODE_ENV: production
      REACT_APP_API_URL: http://3.109.209.75:3000
      REACT_APP_BASE_URL: http://3.109.209.75
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./proxy_params:/etc/nginx/proxy_params:ro
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 