version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: israr123
      POSTGRES_DB: Arbob
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    image: israrahmad/arbob-tech-backend:latest
    environment:
      DATABASE_URL: postgresql://postgres:israr123@postgres:5432/Arbob
      JWT_SECRET: your_jwt_secret_here
      NODE_ENV: production
      PORT: 3000
      HOST_URL: ${HOST_URL:-http://localhost}
      CORS_ORIGIN: ${HOST_URL:-http://localhost}
    command: >
      sh -c "
        echo 'Waiting for postgres...' &&
        while ! nc -z postgres 5432; do
          sleep 1
        done &&
        echo 'Database is ready!' &&
        npx prisma migrate deploy &&
        npx prisma db seed &&
        npm start
      "
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: always

  frontend:
    image: israrahmad/arbob-tech-frontend:latest
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=${HOST_URL:-http://localhost}
      - REACT_APP_BASE_URL=${HOST_URL:-http://localhost}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./proxy_params:/etc/nginx/proxy_params:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: 