version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: arbob-postgres-prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: israr123
      POSTGRES_DB: Arbob
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network
    restart: always

  backend:
    image: israrahmad/arbob-tech-backend:latest
    container_name: arbob-backend-prod
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://postgres:israr123@postgres:5432/Arbob
      JWT_SECRET: your_jwt_secret_here
      CORS_ORIGIN: http://3.109.209.75
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: always

  frontend:
    image: israrahmad/arbob-tech-frontend:latest
    container_name: arbob-frontend-prod
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://3.109.209.75:3000
      - REACT_APP_BASE_URL=http://3.109.209.75
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always

networks:
  app-network:
    driver: bridge
    name: arbob-network-prod
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
    name: arbob-postgres-data-prod
  frontend_build:
    name: arbob-frontend-build-prod 