version: "3.8"

services:
  postgres:
    container_name: arbob-postgres-prod
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: israr123
      POSTGRES_DB: Arbob
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    container_name: arbob-backend-prod
    image: israrahmad/arbob-tech-backend:latest
    environment:
      DATABASE_URL: postgresql://postgres:israr123@postgres:5432/Arbob?schema=public
      JWT_SECRET: your_jwt_secret_here
      NODE_ENV: production
      PORT: 3000
      HOST_URL: http://3.109.209.75:3000
      CORS_ORIGIN: http://3.109.209.75
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    command: >
      sh -c "
        echo 'Waiting for postgres...' &&
        while ! nc -z postgres 5432; do
          sleep 1
        done &&
        echo 'PostgreSQL started' &&
        npm start
      "

  frontend:
    container_name: arbob-frontend-prod
    image: israrahmad/arbob-tech-frontend:latest
    environment:
      NODE_ENV: production
      REACT_APP_API_URL: http://3.109.209.75:3000
      REACT_APP_BASE_URL: http://3.109.209.75
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    name: arbob-network-prod
    driver: bridge
