name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: israrahmad
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push backend
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./backend/Dockerfile
        push: true
        tags: israrahmad/arbob-tech-backend:latest

    - name: Build and push frontend
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./frontend/Dockerfile
        push: true
        tags: israrahmad/arbob-tech-frontend:latest

    - name: Copy deployment files to EC2
      uses: appleboy/scp-action@master
      with:
        host: 3.109.209.75
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "docker-compose.new.yml,deploy.sh"
        target: "/home/ec2-user/arbob-tech-erp"

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: 3.109.209.75
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/arbob-tech-erp
          chmod +x deploy.sh
          sudo ./deploy.sh 